### ISSUE TITLE
There are some compilation errors with the lastest libstratosphere

### ISSUE THREAD

**Issue by JamePeng** [Reisyukaku/ReiNX#83]
it looks like the new libstratosphere had refactored the file structure, the NX_Sysmodules file still used the old version include to implement the function.

/ReiNX/NX_Sysmodules/loader/source/ldr_debug_monitor.hpp:4:10: fatal error: stratosphere/iserviceobject.hpp: No such file or directory
 #include <stratosphere/iserviceobject.hpp>

**Comment by Reisyukaku** [comment]
Yea i thought i'd be nice and just link to that but seems to be causing more harm then good.. so fuckem. Reverted.
also using Boost is a good sign of a filthy noob ;v)

**Comment by JamePeng** [comment]
lol, but  this fix still need the scope_guard.hpp of the boost~

ON_SCOPE_EXIT {
        /* Loader doesn't persist the copied resource limit handle. */
        svcCloseHandle(reslimit_h.handle);
    };

**Comment by Reisyukaku** [comment]
Ah right, I wasnt in the mood to deal with these memes yesterday.. looks like their submodule has submodules and for whatever reason just using git clone recursive submodules or whatever doesnt work alone so i went under NX_Submodules and ran
`git submodule update --init --recursive`
because they  have custom boost shit under include
Anyways i reverted it
73c66b73c4193e23d4da6e9d795f3b42248267b6
just pull that and make sure that /include/boost/ dir has shit in it

**Comment by Reisyukaku** [comment]
theres still a few loose ends i gotta figure out when i get home it seems.. will reopen till then

**Comment by Reisyukaku** [comment]
So uhhh things compile but dont boot because a lot of the updated code is atmo specific shit so idk when ill get around to figuring that out.

**Comment by JamePeng** [comment]
yes, use the lastest compile will boot failed! and I have to open the switch shell remove the battery for release the power.

**Comment by Reisyukaku** [comment]
Everything should work as of  bcfb58dcba87d49103725216f67572d2c8c2bed8

**Comment by Reisyukaku** [comment]
also you dont need to open the switch lol.. just hold power button for 20 seconds
